baseURL = "https://jsonfeed.netlify.com/" #baseURL = "./" or "https://jsonfeed.netlify.com/"
languageCode = "en-gb"
title = "first_site"
theme = "ga-hugo-theme"

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = ["json"]
    delimiter = ""

  [outputs]
    page = ["json","players", "html"]
    home = ["json", "redirect", "html"]
    #teams = ["json"]
    section = ["json", "html"]
    taxonomy = ["json", "players"]

  [outputFormats.players]
    baseName = "players"
    mediatype ="application/json"

  [outputFormats.redirect]
    mediatype = "text/netlify"
    baseName = "_redirects"

  [taxonomies]
    sport = "sports"
    practice = "practices"

  [permalinks]
    page = "/:section/:title/"
