baseURL = "https://jsonfeed.netlify.com/" #baseURL = "./" or "https://jsonfeed.netlify.com/"
languageCode = "en-gb"
title = "first_site"
theme = "ga-hugo-theme"

[mediaTypes]
  # [mediaTypes."text/netlify"]
  #   suffixes = ["json"]
  #   delimiter = ""
  [mediaTypes."text/json"]
    suffix = "json"
  [mediaTypes."text/html"]
    suffix = "html"



  [outputs]
    page = ["json", "html"]#, "players"
    home = ["html", "json", "redirect"]
    #teams = ["json"]
    section = ["json", "html"]
    #taxonomy = ["json", "players"]

  [outputFormats.players]
    baseName = "players"
    mediatype ="application/json"

  [outputFormats.redirect]
    mediatype = "text/netlify"
    baseName = "_redirects"

  [taxonomies]
    sport = "sports"
    practice = "practices"

  [permalinks]
    page = "/:section/:title/"
