baseURL = "./" #baseURL = "http://example.org/"
languageCode = "en-gb"
title = "first_site"
theme = "ga-hugo-theme"

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffixes = ["json"]
    delimiter = ""

  [outputs]
    page = ["html", "json","players"]
    home = ["html", "json", "redirect"]
    teams = ["html", "json"]
    section = ["html", "json"]
    taxonomy = ["html", "json", "players"]

  [outputFormats.players]
    baseName = "players"
    mediatype ="application/json"

  [outputFormats.redirect]
    mediatype = "text/netlify"
    baseName = "_redirects"

  [taxonomies]
    sport = "sports"
    practice = "practices"

  [permalinks]
    page = "/:section/:title/"
